In [1]:
import numpy as np
import tensorflow as tf
import pandas as pd

In [2]:

# Load the training data
train_inputs = pd.read_csv('Audiobooks_data_train_inputs.csv')
train_targets = pd.read_csv('Audiobooks_data_train_targets.csv') 

# Load the validation data
validation_inputs = pd.read_csv('Audiobooks_data_validation_inputs.csv') 
validation_targets = pd.read_csv('Audiobooks_data_validation_targets.csv') 
# Load the test data
test_inputs = pd.read_csv('Audiobooks_data_test_inputs.csv') 
test_targets =pd.read_csv('Audiobooks_data_test_targets.csv') 


### Training

In [3]:
output_size = 2
hidden_layer_size = 50

model = tf.keras.Sequential([
    tf.keras.layers.Dense(hidden_layer_size, activation='relu'), # 1st hidden layer
    tf.keras.layers.Dense(hidden_layer_size, activation='relu'), # 2nd hidden layer
    tf.keras.layers.Dense(output_size, activation='softmax') # output layer
])

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
batch_size = 100
max_epochs = 100


early_stopping = tf.keras.callbacks.EarlyStopping(patience=2)


model.fit(train_inputs, # train inputs
          train_targets, # train targets
          batch_size=batch_size, # batch size
          epochs=max_epochs, # epochs that we will train for (assuming early stopping doesn't kick in)
          callbacks=[early_stopping], # early stopping
          validation_data=(validation_inputs, validation_targets), # validation data
          verbose = 2 # making sure we get enough information about the training process
          ) 

Epoch 1/100
36/36 - 1s - loss: 0.5482 - accuracy: 0.7829 - val_loss: 0.4264 - val_accuracy: 0.8479 - 790ms/epoch - 22ms/step
Epoch 2/100
36/36 - 0s - loss: 0.3780 - accuracy: 0.8670 - val_loss: 0.3472 - val_accuracy: 0.8680 - 85ms/epoch - 2ms/step
Epoch 3/100
36/36 - 0s - loss: 0.3294 - accuracy: 0.8818 - val_loss: 0.3222 - val_accuracy: 0.8702 - 88ms/epoch - 2ms/step
Epoch 4/100
36/36 - 0s - loss: 0.3064 - accuracy: 0.8852 - val_loss: 0.3088 - val_accuracy: 0.8702 - 83ms/epoch - 2ms/step
Epoch 5/100
36/36 - 0s - loss: 0.2899 - accuracy: 0.8935 - val_loss: 0.2881 - val_accuracy: 0.8792 - 94ms/epoch - 3ms/step
Epoch 6/100
36/36 - 0s - loss: 0.2786 - accuracy: 0.8966 - val_loss: 0.2912 - val_accuracy: 0.8837 - 86ms/epoch - 2ms/step
Epoch 7/100
36/36 - 0s - loss: 0.2737 - accuracy: 0.8963 - val_loss: 0.2968 - val_accuracy: 0.8837 - 90ms/epoch - 2ms/step


### test

In [4]:
test_loss, test_accuracy = model.evaluate(test_inputs, test_targets)

14/14 [==============================] - 0s 2ms/step - loss: 0.2814 - accuracy: 0.8951


In [5]:
print('\nTest loss: {0:.2f}. Test accuracy: {1:.2f}%'.format(test_loss, test_accuracy*100.))


Test loss: 0.28. Test accuracy: 89.51%


### Probability for a customer to convert to buy again

In [6]:
model.predict(test_inputs)

14/14 [==============================] - 0s 1ms/step


array([[7.19625056e-01, 2.80374944e-01],
       [9.15601790e-01, 8.43981728e-02],
       [4.56924617e-01, 5.43075442e-01],
       [9.99669909e-01, 3.30083480e-04],
       [9.64658931e-02, 9.03534174e-01],
       [1.30482670e-03, 9.98695195e-01],
       [7.93196023e-01, 2.06803918e-01],
       [8.53082478e-01, 1.46917596e-01],
       [9.99418259e-01, 5.81808272e-04],
       [2.69489101e-06, 9.99997258e-01],
       [8.15159440e-01, 1.84840500e-01],
       [9.80171323e-01, 1.98286455e-02],
       [4.29315358e-01, 5.70684612e-01],
       [4.83347595e-01, 5.16652405e-01],
       [1.15764037e-01, 8.84235978e-01],
       [9.98859286e-01, 1.14068133e-03],
       [1.11978079e-04, 9.99888062e-01],
       [9.87926126e-01, 1.20739155e-02],
       [8.65966618e-01, 1.34033412e-01],
       [8.97240877e-01, 1.02759205e-01],
       [8.06468487e-01, 1.93531498e-01],
       [1.38860360e-01, 8.61139715e-01],
       [8.99297535e-01, 1.00702502e-01],
       [1.37392700e-01, 8.62607241e-01],
       [9.795523

In [7]:
model.predict(test_inputs)[:,1].round(0)

14/14 [==============================] - 0s 2ms/step


array([0., 0., 1., 0., 1., 1., 0., 0., 0., 1., 0., 0., 1., 1., 1., 0., 1.,
       0., 0., 0., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0.,
       1., 0., 1., 1., 0., 1., 0., 1., 0., 0., 0., 0., 1., 1., 0., 1., 0.,
       1., 1., 0., 0., 1., 1., 1., 1., 0., 1., 0., 0., 0., 1., 0., 1., 0.,
       1., 0., 1., 1., 0., 0., 1., 1., 1., 1., 0., 1., 0., 1., 0., 0., 1.,
       0., 0., 1., 0., 1., 1., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 1.,
       1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 0., 1.,
       0., 0., 1., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 1., 1., 1., 0.,
       0., 0., 1., 1., 1., 0., 1., 0., 0., 1., 1., 1., 0., 1., 0., 1., 0.,
       0., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
       1., 1., 1., 0., 1., 1., 0., 1., 1., 0., 1., 1., 0., 0., 1., 0., 1.,
       0., 1., 1., 0., 0., 0., 1., 1., 0., 1., 1., 1., 1., 1., 0., 0., 1.,
       0., 1., 1., 1., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1.,
       1., 1., 0., 1., 1.

In [8]:
np.argmax(model.predict(test_inputs),axis=1)

14/14 [==============================] - 0s 1ms/step


array([0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1,

### Saving the model

In [9]:
model.save('audiobooks_model.h5') 

c:\users\shrijeet kumar\appdata\local\programs\python\python38\lib\site-packages\keras\src\engine\training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
